### ISSUE TITLE
feature: App, Space, and "Sandbox" / "Shelf" or modify "Space" to function more as expected...

### ISSUE THREAD

**Issue by ylluminate** [quanglam2807/webcatalog#1517]
I use WebCatalog and Chromeless to create compartmentalized browsers for customers, concepts and research topics. The more and more I think about things I really don't mind the idea of using Neutron via WebCatalog as a replacement for Epichrome and Coherence X or Chromeless insomuch that usage becomes more similar to individual browsers.

I simply do not use (neither do I want) an "App" approach as it currently exists. I also do not like / want to use the "Space" approach since it doesn't behave in an intuitive fashion. I can "force" Space to kind of work the way I want, but it is labored / difficult to do so.

We very much need a third option that might be termed "Shelf" or "Sandbox" or even "Space", but just redesigned.  The idea is to simply provide a general browser that is customizable like exists in the other aforementioned solutions.  Currently the left sidebar with the "+" button and adding apps within that just does not seem right / intuitive at all.

I want to be able to simply create a comprehensive browser that keeps all cookies / sessions, passwords, bookmarks, extensions, etc. all within a singly named app like "Customer A" or "Banking" or "Local Shopping".

Can we please address this issue?  I feel like WebCatalog is supposed to fill this niche, but it's just not doing it properly right now...

**Comment by quanglam2807** [comment]
Thank you so much for the amazing feedback, @ylluminate! This sounds a lot like the "Multiple Websites" mode in Chromeless, am I right? 

We're currently working on tabs and password autofill support. With those features, Spaces would function a lot more like a traditional browser.

**We very much need a third option that might be termed "Shelf" or "Sandbox" or even "Space", but just redesigned. The idea is to simply provide a general browser that is customizable like exists in the other aforementioned solutions. Currently the left sidebar with the "+" button and adding apps within that just does not seem right / intuitive at all.**
This sounds like something we should consider. But building a browser is not an easy task. Also, if we go ahead with this, how is it different from Chrome profiles?

**Comment by ylluminate** [comment]
Very welcome @quanglam2807. Yes, that is right. The concept is such that it gives you a nice compartmentalized web browser. There is actually enormous marketing potential right now with the push in the media against Google and how it has been allowing cross site tracking and so forth. Basically the world is wanting a browser that can have compartmentalization right now so as to reduce or eliminate cross pollination via cookies, etc.

Yes, tabs and password - making it work as a real web browser - is what is needed. It sounds like making Neutron this core new Electron based browser with traditional web browsing functionality so that we can get out of this Google-break-everything nightmare will help tremendously.  The downfall of Epichrome has been a completely horrible experience and has created a huge nightmare.  Being able to use Brave and Chromium was nice, but ultimately we need reliability and it needs to be what appears to be what you're doing right now by way of Electron.

Chrome profiles are garbage.  I do not and will not trust Google with anything at this point.  I've lost enormous investments from trusting Google and being nuclearized in the end. I think many people feel like this and the news media seems to be pushing against them too.

The workflow that is desirable, for example, is opening a browser called "Local Shopping" and when you do you know that you'll get a reliable restored session with everything you were doing / working on / looking at open right up for you.  Again, I do this with customers and I have about 75 browsers dedicated to different clients and different browsing parameters. Some even use different VPNs  and SOCKS network proxies for different countries and regions due to customer needs and their servers, etc.

Does this make sense?  I'm happy to help brainstorm marketing potential further, but this seems sane and very desirable presently.

**Comment by quanglam2807** [comment]
Thank you so much for the clarification, @ylluminate. After thinking and researching more, I agree that there's a market for this problem. So we'll definitely work to build it. It will be introduced as a new product as we don't really position WebCatalog as a traditional web browser.

- The password autofill feature is ready and will be available with Neutron@20
- We'll work on adding "tabs" to Neutron and get it working by end of October.
- We'll work on the new product based on Neutron after releasing "tabs". MVP would come out quickly but it will take some time for us to polish everything.
- Bookmark & history support will be added to Neutron later.

**Comment by ylluminate** [comment]
Thanks @quanglam2807. I think that makes sense. I was always under the impression that WebCatalog was designed to fill this niche itself, but obviously the "Space" didn't do as I thought. Apps like Epichrome and Coherence X (as I'm sure you know) have essentially two modes for the apps they create: App and Browser.  App is congruent with App in WebCatalog, but Browser (or whatever they name it) is not aligned with "Space" as I had thought was the case and as we're discussing here.

I think you're making a good call.  Obviously no one can trust Google whatsoever except for one thing: there will always be a browser engine that can be used since so many large corporations have bought into it.

This obviously leads to the logic that Electron should always exist because, likewise, there is enormous buy in.

Then by extension, if the appropriate tooling is added, this can be a browser that can be used reliably and without fear of Google terminating it - ie, Neutron. This makes sense and could theoretically become something essentially as big as Electron itself in terms of offering a core browser for people to build from and would thus offer an ecosystem.  Could make for a good open source foundation and donation ask perhaps.  Sounds like a good sweet spot for Neutron itself.

I'm very much looking forward to work in this area, especially since Epichrome is hitting EOL at the end of this year. It would be nice if we could figure out a way to import old Chrome and Brave settings in some fashion (realizing that full session state importation might be difficult / impossible).

**Comment by quanglam2807** [comment]
Thanks @ylluminate. I'll come back with more details later. But have you tried creating browser instance with Chromeless (https://webcatalog.io/chromeless/)? Chromeless also has 2 different modes. If not, it seems like that feature is hidden away because of bad UI design.

**Comment by ylluminate** [comment]
Thanks I have indeed created instances with Chromeless like this and it works - but it feels like it's not as "stable" as Epichrome yet. I've had some various troubles and to be honest with you, I've been worried about using Chromeless because of what happened with the Windows version.  That plug pulling made me feel like the product could end at any point and persuaded me to not really test it as thoroughly as I had planned or to really migrate things over from Epichrome.

Frankly the original intent with moving to something new like Chromeless was to be able to synchronize workflow between various workstations that range from macOS to Windows and Linux.  I personally use 4 workstations (2 macOS + 1 Windows + 1 Linux) for my work.  I want to have a homogenous workflow in some respects, especially in terms of information management and Internet / web usage.  Chromeless was going to be my bridge for that, but of course that can't happen now.

So now, while Epichrome is effectively dead and just in maintenance mode until the end of the year, it is "stable" and seems to continue to function sufficiently to get me to a point where I can make a cohesive jump.

One thing I'd like to add is that with your work on the "new product" based on Neutron, I would very much like to see a way that we can sync settings between computers based on our own sync tools (Syncthing, NextCloud/OwnCloud, Dropbox, etc.). It should, I think, consist of a central folder somewhere that can be synchronized with such a tool and would allow all browser instances + their settings be able to function on other systems.  Does this make sense?

**Comment by quanglam2807** [comment]
Thank you so much for the insights, @ylluminate! We're working to wrap up tab support. After that, I'll work to set the ground up for the new product. 

> One thing I'd like to add is that with your work on the "new product" based on Neutron, I would very much like to see a way that we can sync settings between computers based on our own sync tools (Syncthing, NextCloud/OwnCloud, Dropbox, etc.). It should, I think, consist of a central folder somewhere that can be synchronized with such a tool and would allow all browser instances + their settings be able to function on other systems. Does this make sense?

Currently, the data path is consistent, so if you combine with `rsync`, this is partially possible (the only problem is for custom apps as the app IDs won't be consistent across devices).

Our plan is to complete our product lines first, and then work on a subscription plan that lets users sync apps/accounts/set up easily across devices.

**Comment by ylluminate** [comment]
Any news on this front @quanglam2807? With Epichrome winding down some of us are hunting far and wide for a replacement and need to find a new home ASAP...

**Comment by quanglam2807** [comment]
Currently, I'm the only developer on the team so we don't really have enough resources to work on this soon. In the next few months, I'll mostly focus on turning WebCatalog into a cloud-based business and growing the team. After that, we'll work to address this. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
