### ISSUE TITLE
Media playback is not shown properly in Mac OS

### ISSUE THREAD

**Issue by mustafapc19** [quanglam2807/webcatalog#1519]
# Bug Report
**Specifications:**
- WebCatalog Version: v37.0.0
- Neutron Version: 19.1.0
- OS (macOS, Windows, Linux): macOS

**Description:**
I am using the Youtube app

Media playback is not shown in media playback menu in the top bar of macOS
<img width="307" alt="image" src="https://user-images.githubusercontent.com/35809690/134377005-c895cbcd-2d2d-4f7a-8f10-86b15b448077.png">
the empty one is the entry related to the youtube app I was running

'Pause/Play' button in my touch bar always shows it's not playing anything even when it is playing the youtube video. But clicking it does toggle 'Pause/Play'

I really like the app. I hope this can be fixed. I can try helping if it's ok

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
