### ISSUE TITLE
feature: Copy apps from one Space to another.

### ISSUE THREAD

**Issue by MickMake** [quanglam2807/webcatalog#1520]
# Feature Request
**Specifications:**
- WebCatalog Version: v37.0.0
- Neutron Version:
- OS (macOS, Windows, Linux): All

**Description:**
It'd be nice to be able to copy an app from one "Space" to another. Or at least be able to duplicate a Space.
The reason is that I've created a number of Spaces to organize all my apps, but found that the organization isn't right.
EG: Want to now move "social" apps to a different a new Space to avoid clutter.

If I could copy an entire Space then at least I could remove the unwanted apps, but even better if I could move apps over from one Space to another.

**Additional Context**

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
