### ISSUE TITLE
bug: No Window Border and Control Icons

### ISSUE THREAD

**Issue by KibaNoOu** [quanglam2807/webcatalog#1521]
# Bug Report
**Specifications:**
- WebCatalog Version: v37.0.0 (x64)
- Neutron Version:
- OS (macOS, Windows, Linux): Windows 10 21H1

**Description:**
There's no Window Border and Control Icons (like minimize, restore and close)

**Steps to Reproduce:**
Open any app and there's no window border

**Additional Context**
![immagine](https://user-images.githubusercontent.com/11923117/134469377-c9cb6d14-55f4-46c2-9780-a0eb79b4225b.png)

**Comment by quanglam2807** [comment]
I'm sorry for the problem. Does it happen with newly installed apps? We couldn't reproduce the bug on our machines at all.

**Comment by KibaNoOu** [comment]
Solved uninstalling and reinstalling WebCatalog app and websites.

**Comment by quanglam2807** [comment]
I'm sorry for the trouble. Probably, something has corrupted the apps. If this occurs again, please let us know and we'll try our best to fix it.

**Comment by KibaNoOu** [comment]
After restart the issue is still present.

**Comment by quanglam2807** [comment]
Could you describe all the steps to reproduce the problem?

**Comment by KibaNoOu** [comment]
Found the problem!
If i enable the **Pin window to system tray (notification area)** in **Preferences** the issue appears.

**Comment by quanglam2807** [comment]
Thank you so much! The update with bug fix is now available.
