### ISSUE TITLE
feature: background updater

### ISSUE THREAD

**Issue by mrled** [quanglam2807/webcatalog#1525]
# Feature Request
**Specifications:**
- WebCatalog Version: Version v37.1.1 (x64)
- Neutron Version:
- OS (macOS, Windows, Linux): macOS / all

**Description:**

Would you consider building a background updater than can seamlessly update WebCatalog itself and all apps? My workflow would be much smoother if they were handled for me automatically.

**Additional Context**

Frequently, I'll launch an app I've installed with WebCatalog, and get a notice that there are updates to apply. To apply them, I launch the main WebCatalog app, apply the main update, wait for it to restart, click "Update All" for the list of apps I've installed with WebCatalog, and then wait for them to finish, before relaunching my initial app and doing whatever work I was doing. This flow is a bit cumbersome. Also, I've got ~20 apps installed by WebCatalog, and updating them all in the foreground takes some time.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
