### ISSUE TITLE
feature: shortcut to toggle window always on top

### ISSUE THREAD

**Issue by gaelcharles** [quanglam2807/webcatalog#1526]
# Feature Request
**Specifications:**
- WebCatalog Version: v37.1.1
- Neutron Version:
- OS (macOS, Windows, Linux): macOS

**Description:**
I discovered WebCatalog today and find it amazing. I was looking for a way to make webapps float over my other apps. However, I believe the way we can make windows float over the rest is not very handy: Go to Preferences, Window & Menu Bar, check or uncheck "Keep window always on top", then restart the app. Having a shortcut to make it float/unfloat would be a great feature: something like Ctrl/Cmd+Shift+P to pin/unpin it to the top.
I believe this might be difficult as the app needs to restart to apply changes for now, but there must be a way. Some concurrent apps like Flotato already have such a feature – without the need for the app to be restarted.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
