### ISSUE TITLE
feature: Hide status bar?

### ISSUE THREAD

**Issue by videopilot** [quanglam2807/webcatalog#1527]
# Feature Request
**Specifications:**
- WebCatalog Version: 15.0.0
- Neutron Version: 20.1.0
- OS (macOS, Windows, Linux): macOS

**Description:**

Many simple apps don't really need a status bar popping up at the bottom for every link. It feels out of place for something that should feel like a desktop app, especially when it comes up as white on a dark page.

Please add an option to hide the status bar.

![status](https://user-images.githubusercontent.com/6528746/135322308-10a5c87d-c927-4f6e-ba82-c41d268f403e.gif)

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
