### ISSUE TITLE
bug: JS code injection does not work in Slack app after signing in

### ISSUE THREAD

**Issue by null-dev** [quanglam2807/webcatalog#1531]
# Bug Report
**Specifications:**
- WebCatalog Version: v37.2.1
- Neutron Version: 20.1.0
- OS (macOS, Windows, Linux): Arch Linux (`Linux nd-oc 5.14.8-zen1-1-zen #1 ZEN SMP PREEMPT Sun, 26 Sep 2021 19:36:16 +0000 x86_64 GNU/Linux`)

**Description:**
JS code injection does not work in the Slack app after signing in. E.g. Try injecting the following script: `alert('hi');`.

**Steps to Reproduce:**
1. Install the Slack "app"
2. Sign into a Slack workspace.
3. Configure a JS script to inject.
4. Restart the "app".
5. Observe that the JS script is not injected.

**Comment by quanglam2807** [comment]
Thanks for reporting. It doesn't work because WebCatalog doesn't support alert(). https://docs.webcatalog.io/article/50-does-webcatalog-singlebox-and-clovery-support-all-w3c-web-standards

**Comment by null-dev** [comment]
> Thanks for reporting. It doesn't work because WebCatalog doesn't support alert(). https://docs.webcatalog.io/article/50-does-webcatalog-singlebox-and-clovery-support-all-w3c-web-standards

`alert()` actually works fine for me. For a test I configured the JS injection script to be: `alert("hi");` and it pops up every time the login page loads or I refresh the login page. As soon as I'm logged in though, it stops working.

I also tried other things to test code injection (e.g. `console.log` and even defining a variable) to no avail. I'm pretty sure the script just isn't being run.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
