### ISSUE TITLE
feature: Allow URL protocol handling

### ISSUE THREAD

**Issue by aubreypwd** [quanglam2807/webcatalog#1536]
# Feature Request
**Specifications:**
- WebCatalog Version: Version v37.3.1 (x64)
- Neutron Version: Unknown
- OS (macOS, Windows, Linux):

![image](https://user-images.githubusercontent.com/1753298/136583920-e6461565-0bb5-4dee-8775-91179f7f39c7.png)

**Description:**

Right now use use [Choosy](https://www.choosyosx.com) to e.g. direct `https://github.com/*` to my Github WebCatalog app, it would be really cool to either a) have this pre-configured or b) be able to configure the URL for the app to handle, so when I click on `https://github.com/webcatalog/webcatalog-app/issues/new` it would e.g. open up the Github WebCatalog app automatically.

But, that being said I think we would have to be able to set WebCatalog as the default browser in our system, that being said as well we would also need to set a default browser if an app cannot be figured out via the URL handling feature, e.g. I would set Choosy again as my default browser in WebCatalog, others would set e.g. Safari, Google Chrome, etc.

I also think this feature should be an opt-in feature.

Right now when I install an app, e.g. I just installed Bonsai, I have to go into Choosy and configure the app each time I install it; to make these more app-like it would be cool if Bonsai links just started opening up in that app automatically!

Love WebCatalog! Great work!

**Comment by quanglam2807** [comment]
Thanks for the feedback. We'll try to add this directly into WebCatalog if possible. For now, have you tried Switchbar: https://webcatalog.io/switchbar/? It's like Choosy + WebCatalog support.

**Comment by aubreypwd** [comment]
I did see that app, does it automatically integrate with WebCatalog, or do I also additionally have to configure it when I install an app?

**Comment by aubreypwd** [comment]
> Switchbar will automatically scan for all the apps you installed from WebCatalog and let you quickly open links using the most suitable apps

I will give it a shot, if that works then I don't think we need this request :D

**Comment by aubreypwd** [comment]
Wow Switchbar rocks! I am going to tinker with it more, but I think this is the solution I needed as it has a remember my option, which adds the rule for me!

**Comment by quanglam2807** [comment]
That's great! I can also add an option to always open in WebCatalog apps if possible. Would that be something you want?

**Comment by aubreypwd** [comment]
Not sure I understand the option you're describing? SwitchBar seems to be letting me choose apps for links and remember what app I opened it in, this is almost exactly what I'm describing.

For me this app is probably 100% what I want because
- It replaces Choosy (gives me the same functionality, i.e. Choosing a browser)
- But it also let's me configure links to open in WebCatalog

For me, I think this is what I need 100%... I'm happy to close this issue, as I think it's the answer to the issue (it's just not built in to WebCatalog).

**Comment by aubreypwd** [comment]
So after trying out Switchbar, which worked for most cases, I still actually think this would be a cool option to bake into WebCatalog somehow. Although, I am not sure how that would be possible w/out having to set WebCatalog as the default browser to accomplish.

But, in my circumstance, I would
1. Make Choosy my default browser
2. Make WebCatalog the default browser

And then this means any rules I had in Choosy will take affect first, then it will fallback to WebCatalog who will open the right app for me based on URL handling configured in the App?

**Comment by mikeburgh** [comment]
It would also be nice if you are using a space in WebCatalog that the app you choose to open the link with once you get to WebCatalog was remembered and did not need to be selected each time

**Comment by aubreypwd** [comment]
I know this would be a huge undertaking, but all this also means that WebCatalog would have to maintain the correct URL handling of URL's. E.g. each app would have to have it's own URL handling, and at times these may conflict with spaces.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
