### ISSUE TITLE
feature: add ability to store basic auth

### ISSUE THREAD

**Issue by eitch** [quanglam2807/webcatalog#1544]
# Feature Request
**Specifications:**
- WebCatalog Version: 20.1
- Neutron Version: 20.1
- OS Linux: PopOS! 21.04

**Description:**
Allow possibility to store basic auth credentials

**Additional Context**
I have some applications which require basic auth in addition to the application login. It would be great to be able to store the basic auth.

A perfect state would be if i could define if i want to store only the basic auth, not all credentials.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
