### ISSUE TITLE
bug: Night Eye isn't showing up in list of extensions

### ISSUE THREAD

**Issue by egreenfield** [quanglam2807/webcatalog#1545]
# Bug Report
**Specifications:**
- WebCatalog Version: 38.0.3
- Neutron Version:
- OS (macOS, Windows, Linux): MacOS 11.6

**Description:**
"Night Eye" Chrome extension isn't showing up in the list of extensions that can be enabled.  All other extensions I have in stalled in chrome show up, and Until very recently (not sure what changed), Night EYe was showing up, could be enabled, and was working fine inside of WebCatalog Apps.

**Steps to Reproduce:**

1. Install Night Eye from Chrome store.
2. launch any WebCatalog app.
3. open preferences
4. go to 'extensions' section
Results: Night Eye is not listed, and not available to enable.

**Additional Context**
I've updated all my Web Catalog apps, uninstalled and reinstalled Night Eye from Chrome, refreshed extension list in WebCatalog, etc.

**Comment by egreenfield** [comment]
I heard back from the Night Eye developers: sounds like they updated to a newer version of the extension manifest that is not supported in WebCatalog.  I'm googling around to undersatand the implications, but consider this now an uniformed request that WebCatalog support V3 manifests, whatever that entails :)

**Comment by quanglam2807** [comment]
You're right, @egreenfield. At the moment, WebCatalog doesn't support manifest v3. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
