### ISSUE TITLE
bug: Dark Reader for Google Voice doesn't work properly

### ISSUE THREAD

**Issue by ScottYates** [quanglam2807/webcatalog#1548]
Bug Report
Specifications:

App Version: v38.0.3 (x64)
OS (macOS, Windows, Linux): Windows 10
Description:
I was using the Dark Reader switch with the Google Voice app and it seemed to work well. After the update of WebCatalog to v38.0.3 (x64), the option is unusable, it puts light fonts on white background and the chat windows remain unchanged (white background). System theme is dark.

Steps to Reproduce:
Switch on the Dark Reader setting in Appearance for Google Voice app.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
