### ISSUE TITLE
feature: Option to show badge in side bar, but not space icon

### ISSUE THREAD

**Issue by mikeburgh** [quanglam2807/webcatalog#1549]
# Feature Request
**Specifications:**
Neutron: 20.4.0
Electron: 15.2.0
Node: 16.5.0
Chromium: 94.0.4606.8
OS: Mac OSX

**Description:**
Inside a space you can select to show unread badge count, and enabling it will show it in the sidebar, and the space icon in the dock.

It would be handy to be able to separate that out, so you could just show it in the side bar for some apps, but not have those app's count included in the count on the space icon in the dock.

**Additional Context**
For example, I would like to see the GMail unread count in the sidebar, but not included in the count shown on the space icon in the dock. The count on the space icon in the dock,  I would only like to see unread count from apps for chat (eg things expecting a more immediate response).

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
