### ISSUE TITLE
feature: Show Navigation Bar option doesn't show navigation bar on active window

### ISSUE THREAD

**Issue by katagaki** [quanglam2807/webcatalog#1555]
# Bug Report
**Specifications:**
- WebCatalog Version: 38.0.3 (x64)
- Neutron Version: 20.4.0
- OS (macOS, Windows, Linux): macOS Monterey

**Description:**
When multiple windows are open in one WebCatalog instance (such as when a new window is triggered by the main page), selecting the Show Navigation Bar menu option does not show the navigation bar on the active window, but rather shows it on the main (first) window.

**Steps to Reproduce:**
1. Open a page that supports opening a new window, or has links.
2. Either trigger the new window, or right click on a link and choose Open in New Window.
3. Open the View menu and click Show Navigation Bar.

**Additional Context**
Show Navigation Bar option should show the navigation bar on sub (secondary) windows as well to provide the additional functionality when necessary.

**Comment by quanglam2807** [comment]
Thanks for bringing this up. Popup windows at the moment doesn't have as many features as the main window. We'll try add navigation bar and other features to the popup windows soon.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
