### ISSUE TITLE
feature: Add a Preference to Accounts to opt-out of Hibernation individually

### ISSUE THREAD

**Issue by marcusquinn** [quanglam2807/webcatalog#1557]
# Feature Request
**Specifications:**
- WebCatalog Version: Latest
- Neutron Version: Latest
- OS (macOS, Windows, Linux): All

**Description:**
Add a Preference to Accounts to opt-out of Hibernation individually.

**Additional Context**
As an example; say I have one Webcatalog App wrapper, with 10 Accounts/Sites in. I might want to hibernate all but one or two of them.

**Comment by marcusquinn** [comment]
Any chance of a nudge on this please?

**Comment by quanglam2807** [comment]
Will try, @marcusquinn!

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
