### ISSUE TITLE
feature: Backing up accounts within space

### ISSUE THREAD

**Issue by katagaki** [quanglam2807/webcatalog#1562]
# Feature Request
**Specifications:**
- WebCatalog Version: 40.0.0 (x64)
- Neutron Version: 20.5.0
- OS (macOS, Windows, Linux): macOS

**Description:**
Back up the space's accounts as well when using the 'Backup and restore apps & spaces' feature to transfer entire spaces quickly between Macs.

**Additional Context**
Currently, 'Backup and restore apps & spaces' simply backs up and restore the space itself, but the restored space contains no accounts.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
