### ISSUE TITLE
feature: ability to slide webcatalog app/window to the edge of the screen and out of view using hotkey or gesture

### ISSUE THREAD

**Issue by zendude213** [quanglam2807/webcatalog#1565]
# Feature Request

**Description:**

Apart from single apps, I also use a WebCatalog "Space" to organize and have quick access to my messaging apps. While I know I can pin it on the menu bar, the experience feels a lot more natural if I can slide it out to the right or left edge of my screen 

Some examples of what I'm trying to convey:

- Vivaldi's [Web Panel feature ](https://vivaldi.com/blog/teamblog/vivaldi-web-panel-top-sites/)
- [Tuck](https://www.producthunt.com/posts/tuck-1)
- [Slidepad](https://slidepad.app/)

If you combine this UX with Extensions, then I think Webcatalog would be unstoppable

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
