### ISSUE TITLE
bug: New app Spotify installed with WebCatalog 40.2.0 hangs on 10.11

### ISSUE THREAD

**Issue by MacTerrassa** [quanglam2807/webcatalog#1576]
# Bug Report
**Specifications:**
- WebCatalog Version: 40.2.0
- Neutron Version: 
- OS (macOS, Windows, Linux): 10.11.6

**Description:**

Before updating WebCatalog, it was working fine. I update WebCatalog to 40.2.0 and the Spotify app to 21.4.3 and now the window opens, but pressing any play button crashes and closes immediately.
**Steps to Reproduce:**

Open the Spotify app. Search for album, or those that appear on the home screen. Press play. Lock and close.
**Additional Context**

I have uninstalled all installed WebCatalog apps from within the program. I have searched for all related folders within my user library and deleted them. I only reinstall Spotify. Still the same. The only change between the previous week, and after updating and before opening Spotify, has been to have purchased a WebCatalog license. Which continues to recognize correctly.
On console, I don't get any separate error messages, but if I clear the screen and try to open Spotify.app again, I get the following messages:
30/11/21 12:57:41,912 launchservicesd[91]: SecTaskLoadEntitlements failed error=22
30/11/21 12:57:41,924 launchservicesd[91]: SecTaskLoadEntitlements failed error=22
30/11/21 12:57:44,491 com.apple.xpc.launchd[1]: (com.apple.CoreLocationAgent[5622]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.CoreLocation.agent
30/11/21 12:57:44,640 appleeventsd[59]: SecTaskLoadEntitlements failed error=22
30/11/21 12:57:44,840 sharedfilelistd[364]: SecTaskLoadEntitlements failed error=22
30/11/21 12:57:44,847 locationd[96]: SecTaskLoadEntitlements failed error=22
30/11/21 12:57:45,356 Spotify Helper (GPU)[5623]: [12:57:45.354] vtDecompressionDuctCreate signalled err=-8973 (err) (Could not select and open decoder instance) at /Library/Caches/com.apple.xbs/Sources/CoreMedia_frameworks/CoreMedia-1731.15.207/Sources/VideoToolbox/VTDecompressionSession.c line 1296
30/11/21 12:57:45,444 Spotify Helper (GPU)[5623]: <<<< VTVideoEncoderSelection >>>> VTSelectAndCreateVideoEncoderInstanceInternal: no video encoder found for 'avc1'
30/11/21 12:57:45,444 Spotify Helper (GPU)[5623]: [12:57:45.444] VTSelectAndCreateVideoEncoderInstanceInternal signalled err=-12908 (err) (Video encoder not available) at /Library/Caches/com.apple.xbs/Sources/CoreMedia_frameworks/CoreMedia-1731.15.207/Sources/VideoToolbox/VTVideoEncoderSelection.c line 1308
30/11/21 12:57:45,444 Spotify Helper (GPU)[5623]: [12:57:45.444] VTCompressionSessionCreate signalled err=-12908 (err) (Could not select and open encoder instance) at /Library/Caches/com.apple.xbs/Sources/CoreMedia_frameworks/CoreMedia-1731.15.207/Sources/VideoToolbox/VTCompressionSession.c line 1003
30/11/21 12:57:47,012 sandboxd[189]: ([558]) storeinappd(558) deny file-read-data /private/var/db/DetachedSignatures
30/11/21 12:57:47,648 pkd[365]: SecTaskLoadEntitlements failed error=22
30/11/21 12:57:49,546 launchservicesd[91]: SecTaskLoadEntitlements failed error=22
30/11/21 12:57:49,547 launchservicesd[91]: SecTaskLoadEntitlements failed error=22
30/11/21 12:58:07,941 coreaudiod[207]: SecTaskLoadEntitlements failed error=22
30/11/21 12:58:09,141 chrome_crashpad_handler[5619]: [1130/125809.138908:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7fff54785000, 0x2000): (os/kern) invalid address (1)
30/11/21 12:58:09,628 com.apple.xpc.launchd[1]: (com.webcatalog.juli.spotify.757792[5615]) Service exited due to signal: Segmentation fault: 11
30/11/21 12:58:29,205 secinitd[5679]: UID[0]: cache loaded: /System/Library/Caches/com.apple.app-sandbox-cache.plist
30/11/21 12:58:29,207 secinitd[5679]: ctkd[5678]: unable to get root path for bundle of main executable: /System/Library/Frameworks/CryptoTokenKit.framework/ctkd

Regards
MacTerrassa

**Comment by MacTerrassa** [comment]
I just updated the Spotify app to version 21.7.3 which corresponds to electron 16.0.4 and it gives the same result. It opens, it continues with the identified user but when pressing any button to execute it closes immediately. I have also tried installing Singlebox and activating Spotify, with the same result. Is it still compatible with 10.11 systems or not?

**Comment by quanglam2807** [comment]
I'm sorry for the problem. Would you mind trying this: https://docs.webcatalog.io/article/68-why-do-i-receive-connection-error-on-macos-10-11?
