### ISSUE TITLE
feature: Don't show site's name in the title bar

### ISSUE THREAD

**Issue by maxoku** [quanglam2807/webcatalog#1583]
# Feature Request
**Specifications:**
- WebCatalog Version: Version v40.3.0 (x64)
- Neutron Version: 21.8.1
- OS (macOS, Windows, Linux): Windows 8.1

**Description:**

An option to not display the current's site name in the title bar. I would like only the app's name in the titlebar. E.g. in Messenger app it's `Messenger - Messenger`. I would like just a single Messenger to be displayed there.

**Additional Context**

![image](https://user-images.githubusercontent.com/17256400/146785428-a6f6984f-0c77-40f2-9ba7-7a5da64aba13.png)

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
