### ISSUE TITLE
feature: Allow to put buttons in title bar

### ISSUE THREAD

**Issue by maxoku** [quanglam2807/webcatalog#1586]
# Feature Request
**Specifications:**
- WebCatalog Version: Version v40.3.0 (x64)
- Neutron Version: 21.8.1
- OS (macOS, Windows, Linux): Windows 8.1

**Description:**

I would like to have access to some extension buttons without having whole navigation bar visible. There could be an option to put chosen buttons in the title bar. Or just put all buttons from navigation bar in the title bar when hidden like with navigation buttons. There just could be a setting that would do that.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
