### ISSUE TITLE
bug: No notifications

### ISSUE THREAD

**Issue by maxoku** [quanglam2807/webcatalog#1587]
# Bug Report
**Specifications:**
- WebCatalog Version: Version v40.3.0 (x64)
- Neutron Version: 21.8.1
- OS (macOS, Windows, Linux): Windows 8.1

**Description:**

There are no notifications or setting to turn them on. When I click on control notifications I have only options to mute them. When I click on test notifications nothing happens.

**Steps to Reproduce:**

Go to Preferences > Notifications and click on "Test notifications".

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
