### ISSUE TITLE
feature: Add support for 24 hour clock format

### ISSUE THREAD

**Issue by maxoku** [quanglam2807/webcatalog#1588]
# Feature Request
**Specifications:**
- WebCatalog Version: Version v40.3.0 (x64)
- Neutron Version: 21.8.1
- OS (macOS, Windows, Linux): Windows 8.1

**Description:**

Seems like the app (not website) supports only 12 hour clock format. Though I found time only in setting of mute notifications schedule I would really like a proper display of time anyway.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
