### ISSUE TITLE
feature: Add the possibility to set authentication credentials in the | Network → Proxies | section (especially SOCKS5 and HTTPS ones)

### ISSUE THREAD

**Issue by 2dRYoMz7XKx3Bii** [quanglam2807/webcatalog#1589]
SPECIFICATIONS ↓

WebCatalog Version: Version v40.2.0 (x64)

Neutron Version: 21.7.3

OS (macOS, Windows, Linux): Windows

Description: I had read somewhere that this in particular was a not-so-possible feature, is it still so given the nature of Eletcron and Chromium? In case "IT" (the situation) have made progress I would kindly ask if it would be possible to implement it in the time needed, thank you very much... have a nice day programmers!

![dOCcj8gt1G](https://user-images.githubusercontent.com/77741077/147083617-99beffaa-7626-4bdb-bfb7-478b03f9eeeb.png)

**Comment by fmocking** [comment]
I'm supporting this. To support the development I purchased the full version of the web catalog. I was surprised when I see authentication parameters were missing. Also changing proxy requires a full reboot of the application. Maybe it can be possible to reboot the client only while keeping the container open?

Thanks

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.

**Comment by 2dRYoMz7XKx3Bii** [comment]
---

> I'm supporting this. To support the development I purchased the full version of the web catalog. I was surprised when I see authentication parameters were missing. Also changing proxy requires a full reboot of the application. Maybe it can be possible to reboot the client only while keeping the container open?
> 
> Thanks

---

An alternative that I have implemented is to enable on the chosen proxies provider that authentication is done via IP, hope it helps in the meantime [fmocking](https://github.com/fmocking) !
