### ISSUE TITLE
function: Add ability to manage (generally or specifically) cookies as Cookie AutoDelete [3.6.0] or allow through another section called "Cookie Management" (example) modeled after Chromium to block both first and third party requests

### ISSUE THREAD

**Issue by 2dRYoMz7XKx3Bii** [quanglam2807/webcatalog#1590]
SPECIFICATIONS ↓

WebCatalog Version: Version v40.2.0 (x64)

Neutron Version: 21.7.3

OS (macOS, Windows, Linux): Windows

Description: As per title I would like to create a new section for a more in-depth management of cookies in case the implementation of the elaborated inspired to the mentioned extension is not possible. Thanks again, to the next time! 

![chrome_P8ZwZMz5Dm](https://user-images.githubusercontent.com/77741077/147086856-263ea16d-f41e-4b31-ac1b-bb8166ee8ece.png)

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
