### ISSUE TITLE
bug: pitch to zoom not working in Gmail after restart

### ISSUE THREAD

**Issue by itkind** [quanglam2807/webcatalog#1591]
# Bug Report
**Specifications:**
- WebCatalog Version: 40.3.0
- Neutron Version: 
- OS: MacOS arm64

**Description:**
Pitch to zoom works after installation of Gmail. After I close the app and start Gmail again, no gestures are working and no zoom. 

**Steps to Reproduce:**
install Gmail try to zoom in gesture, close it and start again.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
