### ISSUE TITLE
feature: add menubar command Copy Title

### ISSUE THREAD

**Issue by mdbraber** [quanglam2807/webcatalog#1592]
# Feature Request
**Specifications:**
- WebCatalog Version: 40.3.0
- Neutron Version:
- OS macOS Moneterey

**Description:**
There's already a "Copy URL" item. It woudl be very hulpful to also have a "Copy Title" item e.g. when using apps like [Hook](http://hookproductivity.com). It can simply be the output from `document.title`. Thanks for considering!

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
