### ISSUE TITLE
bug: Forced spellchecker without settings in WebCatalog main app

### ISSUE THREAD

**Issue by maxoku** [quanglam2807/webcatalog#1593]
# Bug Report
**Specifications:**
- WebCatalog Version: Version v40.3.0 (x64)
- Neutron Version:
- OS (macOS, Windows, Linux): Windows 8.1

**Description:**

When I type a text in a search field to find an app it gets spellchecked. The same with name field when adding a custom app. And not even in English, but my native language while app is in English. There are no settings to change the language or even disable it. It's annoying and unnecessary. There shouldn't be any spellchecker in this app in the first place.

**Steps to Reproduce:**

Just type a text in a search or name field.

**Additional Context**

![image](https://user-images.githubusercontent.com/17256400/147397843-4a26bf56-a84e-415b-8549-d67033259016.png)

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
