### ISSUE TITLE
feature: Add "1) Open link in a NEW background window (in the program we don't have tabs)" like the neat Vivaldi browser, "2) Copy link text & Copy Link (final!) address" and "3) Image" (commands?) in the right click menu

### ISSUE THREAD

**Issue by 2dRYoMz7XKx3Bii** [quanglam2807/webcatalog#1596]
Specifications:

- WebCatalog Version: 21.11.1

- Neutron Version: 21.11.1

- OS (macOS, Windows, Linux): Windows 10 Pro N 21H2 (19044.1415)

Description:
As you can see from the images below I would like to have much more choice in the context menu with the pressing of the right button and to possibly HAVE implemented a good part of the suggestions put here in the request, thanks again, your WebCatalog rocks!

![#1](https://user-images.githubusercontent.com/77741077/147701270-d06d241a-d3c9-4704-b165-32cdc2ad7c55.png)

![#2](https://user-images.githubusercontent.com/77741077/147701276-2dd95245-9247-44b7-af7d-2dd52b5c71f6.png)

**Comment by 2dRYoMz7XKx3Bii** [comment]
Regarding the commands of the drop-down menu I must point out that some FOR the "images options" are already present and available so refer only to those that are not there (OBVIOUSLY) and that it would make sense logically to add to further improve accessibility and functionality, thank you for the attention!

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
