### ISSUE TITLE
feature: Add the possibility to delete navigation data individually for each "component" by ticking various boxes (like the second image at the bottom) not entirely with only a """warning""" AND allow additional NEW windows that can be opened from within the app/program (like the first, second, third etc.) to memorize/remember/store the last own size and position and to reopen in the same way (hypothesis: Using command line parameters [example: --window-size=1280,1024 --window-position=0,0] "internally" ONLY for the NEW windows hierarchically generated maybe?)

### ISSUE THREAD

**Issue by 2dRYoMz7XKx3Bii** [quanglam2807/webcatalog#1597]
Specifications:

WebCatalog Version: 21.11.1

Neutron Version: 21.11.1

OS (macOS, Windows, Linux): Windows 10 Pro N 21H2 (19044.1415)

Description:
I would like to have more control over what I delete from my browsing data and I would like the new windows to reopen with the same size and position since too many times I find myself forced to resize them and I waste time... thank you infinitely to the work of the team of developers BECAUSE without them we would not even have this wonderful program!

![#3](https://user-images.githubusercontent.com/77741077/147702208-2c58a4e7-25b2-42fb-9460-6cce4cbde87d.png)

![#4](https://user-images.githubusercontent.com/77741077/147702217-ec665437-753b-4ee0-9f99-997cd79ebb0b.png)

Guidance on parameters to be set via command line → https://peter.sh/experiments/chromium-command-line-switches

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
