### ISSUE TITLE
feature: Add the ability to create presets of sorts (accessible from the main screen) in order to transpose the internal global preferences of each application to such an extent that you don't have to re-enter the same parameters every time you create a new app OR the ability in the cloning process to actually transport all of them to the new cloned app AND add the possibility of being able to insert in the choice of the search engine a custom one with directly the URL query (like the second screenshot at the bottom of the ticket request)

### ISSUE THREAD

**Issue by 2dRYoMz7XKx3Bii** [quanglam2807/webcatalog#1598]
Specifications:

WebCatalog Version: 21.11.1

Neutron Version: 21.11.1

OS (macOS, Windows, Linux): Windows 10 Pro N 21H2 (19044.1415)

Description:
I need to create presets so that I don't have to re-enter the parameters "300.000 times" (joke there ←) and always click on the same entry and "buttons" (suggestion: moving MISCELLANEOUS below and inserting GLOBAL PREFERENCES PRESETS [creating from scratch the "layout" obviously] above [not exactly like the picture but the place should be about that]) and if possible add the icing on the cake that would be to be able to enter your own query URL of your favorite search engine... that's all for now, thank you very much again for the professionalism and the excellent program developed, to the FOLLOWING need!

![#6](https://user-images.githubusercontent.com/77741077/147705572-61a631b2-4b82-4946-9c20-9ae5acf127f3.png)

![#5](https://user-images.githubusercontent.com/77741077/147705567-bef7d372-31bf-444f-9e08-f0931a510489.png)

**Comment by ylluminate** [comment]
You might want this actually from what you're describing: https://github.com/webcatalog/webcatalog-app/issues/1517#issuecomment-923065729

**Comment by 2dRYoMz7XKx3Bii** [comment]
Yes, I had seen the thread before but I thought there had been updates while instead of that schedule cited has been come very little, we hope that the programmers are still working on it.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
