### ISSUE TITLE
bug: BrowserView size is miscalculated when window is focused on Windows

### ISSUE THREAD

**Issue by lisabettefay** [quanglam2807/webcatalog#1599]
# Bug Report
**Specifications:**
- WebCatalog Version: v40.3.0 (x64)
- Neutron Version: Neutron: 21.11.1
- OS (macOS, Windows, Linux): Windows 10

**Description:**

(resubmitting as a github issue - previously submitted via email)  after leaving the app window (a space in webcatalog or a straight app) idle for a period of time, when i return the window, it is often only showing about 1/4 of the screen (see screenshot below).  i would expect that the window contents would be viewable anytime that i switched to that app, but there seems to be a bug. i can refresh/reload the page and that fixes the visibility, but is annoying to have to do 15x a day.

**Steps to Reproduce:**

i havent been able to pinpoint what triggers it, but it happens pretty much every session, and multiple times per day.

**Additional Context**

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/81186147/147841522-34f19bcc-61fe-4db4-af2d-0fefa4a456cd.png">

edit: 1. it used to be 1/16th of the screen, so it has improved since i first reported it. 2. i forgot to say THANK YOU. : )

**Comment by lisabettefay** [comment]
hm. the blurring was me wiping personal info. the miscalculation seems to be when the window has sat idle and then is called on to be the 'focus window' (aka the one i want to be working in). just clarifying in case my report was confusing. thank you, quang!

**Comment by quanglam2807** [comment]
Thank you so much, @lisabettefay! I'll release an update shortly with a potential fix (in 30-60 minutes). I don't know if it is the correct fix, so please give a try and let me know.
