### ISSUE TITLE
Enable the ""emulation"" (or force mobile rendering to a deep level) of the Android application environment allowing the modification of UserAgent API parameters and device details (as in the image of this ticket, screenshot taken from Mass Planner) implementing the use of both the Linux subsystem on Windows 10 and Capacitator |https://capacitorjs.com| (just examples) to extend access to powerful native APIs and Native UI emulated with WSL 2 (dah) and making them communicate with WebCatalog to simulate the execution NATIVELY of social media (manly my concern) such as Instagram, Facebook as it happens on real smartphone devices

### ISSUE THREAD

**Issue by 2dRYoMz7XKx3Bii** [quanglam2807/webcatalog#1600]
---
Specifications ↓

(WebCatalog, x64) Version 21.11.2
Neutron: 21.11.2
Electron: 16.0.5
Node: 16.9.1
Chromium: 96.0.4664.55
OS: Windows 10 Pro N 21H2 (19044.1415)

---
Description ↓

I know the request goes beyond what Web Catalog is intended to do BUT I think there's a niche that would like to see those kinds of implementations PRESENT. Since "automation" is a HOT topic right now and this would be a really interesting step. But my real question is: Out of my technical knowledge, is this really possible? If it is, I would love to see the changes in the developers section of the general settings inside the app, thank you very MUCH... to the next one!

---

![Rambox Pro](https://user-images.githubusercontent.com/77741077/148067037-e1231ae9-5974-4dae-bd4a-fba08fc4af64.png)

![Here](https://user-images.githubusercontent.com/77741077/148067055-3ebd15ef-455d-42f6-9586-2df5a4f17acf.png)

![Mass Planner](https://user-images.githubusercontent.com/77741077/148067672-8956197b-2967-44d4-a1d1-4f1ab66613dd.png)

**Comment by quanglam2807** [comment]
This option is now available in Neutron v22.0.0 (beta channel)
