### ISSUE TITLE
bug: Whenever the window's focus of an app is changed and enough time passes (15-25 min), the window that I retrieve (the last one) freezes AND become unresponsive... the only temporary fix is to resize the window (as soon as I can get the "problem on tape", I will add the clip to the ticket) and magically the problem is solved, why is that?

### ISSUE THREAD

**Issue by 2dRYoMz7XKx3Bii** [quanglam2807/webcatalog#1601]
---

Specifications ↓

(WebCatalog, x64) Version 21.11.2
Neutron: 21.11.2
Electron: 16.0.5
Node: 16.9.1
Chromium: 96.0.4664.55
OS: Windows 10 Pro N 21H2 (19044.1415)

---

Description ↓

As per the title, I find myself bewildered when this kind of bug happens to me and it is happening to me really way too much. Every time I leave a window in the background and once the indicated time has passed the window doesn't respond anymore if I don't resize it... I think I'm not the only one to whom this happens and I would like to understand if it is a known problem or if there hasn't been anyone who has pointed it out yet... thanks again WebCatalog support, you rocks!

---

Steps to Reproduce ↓

1) Open a WebCatalog app

2) Open another app (not related to Web Catalog) and put the focus on it for 15 minutes

3) Observe the behavior and make your own assessments

---

P.S: Any other important material that will help solve the problem and understand it better will "arrive" in the following days (if needed)

---

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
