### ISSUE TITLE
bug: Google Duo app isn't working

### ISSUE THREAD

**Issue by marco-IT** [quanglam2807/webcatalog#1602]
# Bug Report
**Specifications:**
- WebCatalog Version: 40.3.0.0
- Neutron Version: 21.12.0.0
- OS (macOS, Windows, Linux): Windows 10 Pro 21H1 Build 19043.1415

**Description:**
The Google Duo App isn't working. After login in using my personal account (with 2FA), every time the URL https://admin.google.com/google.com/ServiceNotAllowed is displayed saying I do not have access to this service. In my regular Chrome browser, all works fine.
In the WebCatalog app settings, I've set https://duo.google.com/?web as the home page, tried to call this website by changing the URL in another working Google app (Meet) in my WebCatalog space, and manually inserted the current custom user agent for Chrome on Windows 10 under Developers settings, but nothing works.
I've also tried it with another personal Google account (without 2FA) in a separate test space with no other apps in it - same problem.

**Steps to Reproduce:**
See above.

**Additional Context**
---

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
