### ISSUE TITLE
bug: Navigation and side bars visible in fullscreen

### ISSUE THREAD

**Issue by maxoku** [quanglam2807/webcatalog#1603]
# Bug Report
**Specifications:**
- WebCatalog Version: v40.3.0 (x64)
- Neutron Version: 21.12.0
- OS (macOS, Windows, Linux): Windows 8.1

**Description:**

After entering the full screen navigation bar and sidebar are still visible, they shouldn't.

**Steps to Reproduce:**

Enable showing Navigation Bar or/and Sidebar
Enter full screen mode.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
