### ISSUE TITLE
bug: Every time I try to upload a file of any format through WebCatalog avoiding in every possible way to rename it with illegal characters on Terabox (cloud service) I get the same error: "Illegal file names" but it is not a problem of the platform nor of my wrong renaming, please correct it urgently!

### ISSUE THREAD

**Issue by 2dRYoMz7XKx3Bii** [quanglam2807/webcatalog#1604]
Specifications ↓

(WebCatalog, x64) Version 21.11.2
Neutron: 21.12.0
Electron: 16.0.6
Node: 16.9.1
Chromium: 96.0.4664.110
OS: Windows 10 Pro N 21H2 (19044.1415)

---

Description ↓

The title is self-explanatory! I'm sure it's an internal problem in WebCatalog because both with Chromium and Edge it works the uploading!

---

Steps to Reproduce ↓

1) Create a Terabox app (I haven't changed a single setting)
2) Try to upload something
3) Error "Illegal file names" appears without having uploaded properly anything

---

![illegal-file-names](https://user-images.githubusercontent.com/77741077/148403736-a3efeac4-ce17-471f-bf25-b653a06047dc.png)

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
