### ISSUE TITLE
feature: Allow to choose a default output sound device

### ISSUE THREAD

**Issue by maxoku** [quanglam2807/webcatalog#1605]
# Feature Request
**Specifications:**
- WebCatalog Version: v40.3.0 (x64)
- Neutron Version: 21.12.0
- OS (macOS, Windows, Linux): Windows 8.1

**Description:**

I watch a streaming service (in Singlebox cuz DRM, but it applies to all apps) on the secondary monitor (tv connected with HDMI cable). I like also sound to come from my tv. For any other app I use a program called Audio Router, but it doesn't work on browsers and also on WebCatalog apps.

 In Chromium browsers I use an add-on called AudioXout. Unfortunately it has problems. It needs to work through a microphone channel and it doesn't remember devices. After every refresh I need to change the device again. It can only be changed through the button in navigation bar. So every time I have to open Preferences window, enable it, change the device and disable the bar again (cuz it's visible in full screen while watching).

So a lot of work to watch a video. It would be really nice if without any add-ons I could only once set the default device and it will always be used automatically in that app.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
