### ISSUE TITLE
bug: CLONE doesn't work (as expected)

### ISSUE THREAD

**Issue by marco-IT** [quanglam2807/webcatalog#1606]
# Bug Report
**Specifications:**
- WebCatalog Version: 40.3.0.0
- Neutron Version: 21.12.0.0
- Electron: 16.0.6
- Chromium: 96.0.4664.110
- OS (macOS, Windows, Linux): Windows 10 Pro 21H1 Build 19043.1415

**Description:**
No matter if cloning an app or space, neither the accounts or apps inside will be cloned, nor some specific settings made to the source app/space (e.g. Appearance - show sidebar or navigation bar).

**Steps to Reproduce:**
\-

**Additional Context**
Further, there is no content in the documentation for cloning Spaces.

**Comment by simondsmason** [comment]
Rename a space is actually a different feature.  In the app currently it tells you that you cannot rename a space without cloning it.  So I just did this, and all I got was an empty space that I could name anything I want.  Worse, I uninstalled the original space before I checked the cloned space!

This is not cloning.  Cloning as the original poster stated means copying everything - apps, settings, etc.

Agreed that a rename space feature is needed.  But I think the cloning needs to be looked at - or removed from the app as it currently exists to avoid further user confusion?  Thanks.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
