### ISSUE TITLE
feature: Rename a Space 

### ISSUE THREAD

**Issue by marco-IT** [quanglam2807/webcatalog#1607]
# Feature Request
**Specifications:**
- WebCatalog Version: 40.3.0.0
- Neutron Version: 21.12.0.0
- Electron: 16.0.6
- Chromium: 96.0.4664.110
- OS (macOS, Windows, Linux): Windows 10 Pro 21H1 Build 19043.1415

**Description:**
Like to have the ability to rename a Space. 
(The hint _This cannot be changed. To customize the name, clone [...]._ is nice, but cloning doesn't work currently - see #1606.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
