### ISSUE TITLE
Does not auto complete/find addresses when typing in location in Google Calendar

### ISSUE THREAD

**Issue by Proggie** [quanglam2807/webcatalog#1608]
I created an app for Google Calendar.
When I create an appointment using the app and try to add a location, typically Google Calendar would auto complete the address as you type. In the WebCatalog app this does not happen, and the address is not looked up so it's unclear whether you typed in the correct address. This is the case for both the quick sheet when you first create an appointment as well as if you edit an existing one.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
