### ISSUE TITLE
feature: Support Multiple Windows of same app in WebCatalog Apps

### ISSUE THREAD

**Issue by bcb44** [quanglam2807/webcatalog#1609]
# Feature Request
**Specifications:**
- WebCatalog Version: Version v40.3.0 (x64)
- Neutron Version: 21.12.0
- OS (macOS, Windows, Linux): macOS

**Description:**

It'd be really awesome if web catalog could have multiple windows of the same app running at the same time. I'm using google docs right now and want to work on two different ones at once. This request might be better placed on the Neutron repo but couldn't find the issues portion on that. 

**Additional Context**

**Comment by bcb44** [comment]
Solution for this in Google products is to open one file (can't be a blank doc) and then click File -> Open and open another document. This will open in another window. This works on macOS

**Comment by quanglam2807** [comment]
It's now possible. You just need press Cmd+N or Ctrl+N (from the menu bar: File > New Window)

**Comment by bcb44** [comment]
Thats awesome, thanks - great feature
