### ISSUE TITLE
feature: Biometric / Windows Hello

### ISSUE THREAD

**Issue by OmiCron07** [quanglam2807/webcatalog#1610]
Is it possible to use biometric / Windows Hello passwordless authentication? In Chrome, my extension has this option:

![image](https://user-images.githubusercontent.com/31325575/148874960-469e48d1-c494-4371-ae4f-f8e46845c801.png)

But when installing in WebCatalog, I do not get that option.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
