### ISSUE TITLE
feature: Allow Switchbar to map to apps inside WebCatalog spaces

### ISSUE THREAD

**Issue by twmills** [quanglam2807/webcatalog#1611]
# Feature Request
**Specifications:**
- WebCatalog Version: Version v40.3.0 (arm64)
- OS: macOS

**Description:**
I am paying customer using WebCatalog spaces with Switchbar and I love it. If it could be possible to map to an app _inside_ a space, this would make this set up perfect.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
