### ISSUE TITLE
feature: Make setting "Block ads and trackers" global for all apps

### ISSUE THREAD

**Issue by miguelrs** [quanglam2807/webcatalog#1612]
# Feature Request

**Description:**

It would be nice if the "Privacy > Block ads and trackers" setting could be set globally in WebCatalog, so any app installed will inherit that setting. Currently, I want to block ads in all (or almost all) my apps, it's a bit of a pain having to remember to go to settings, enable it, and restart the app every time I install a new app.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
