### ISSUE TITLE
feature: What would it take to make Augumented Steam (a really GREAT extension from Isthereanydeal) work on WebCatalog?

### ISSUE THREAD

**Issue by 2dRYoMz7XKx3Bii** [quanglam2807/webcatalog#1613]
Specifications ↓

Neutron: 21.12.0
Electron: 16.0.6
Node: 16.9.1
Chromium: 96.0.4664.110
OS: Windows 10 Pro N 21H2 (19044.1466)

Description ↓

This is a request, but also a proposal to improve and add specifications for the operation of some of the most important extensions that many Webcatalog users use in their daily lives. But now let's talk about Augumented Steam...

![image](https://user-images.githubusercontent.com/77741077/150162720-a34ef0aa-9743-47ce-85ca-d9062a7b11ac.png)

The extension loads correctly but unfortunately it does not save the customizable settings in the menu since it would open (by clicking on Settings) a custom link depending on the browser you are using, i.e. → chrome-extension://user_name/html/options.html

![image](https://user-images.githubusercontent.com/77741077/150163373-502439ec-33a0-4b15-8ac7-6ee73c1a99a9.png)

By copying and pasting the link from Vivaldi, Chrome or Chromium, however, it is not possible to make the changes remain... does it have to do with how DOM storage is managed in Web Catalog?

I will wait for clarifications, thanks

**Comment by quanglam2807** [comment]
Currently, extension support is experimental so it doesn't work with a lot of extensions. We'll work to improve it.

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
