### ISSUE TITLE
feature: Manual password save

### ISSUE THREAD

**Issue by maxoku** [quanglam2807/webcatalog#1614]
# Feature Request
**Specifications:**
- WebCatalog Version: v40.3.0 (x64)
- Neutron Version: 21.12.0
- OS (macOS, Windows, Linux): Windows 8.1

**Description:**

Apps don't always offer to save passwords. So it would be nice if I could just add manually logins and passwords to be used. It's frustrating to have to type passwords every time when there is a function for that, but it can't be used, cuz there is no password stored.

**Comment by quanglam2807** [comment]
Currently, the autofill feature is limited and can't detect username/password forms on many websites. We'll work to improve it. For now, even if you add the username/password manually, because the app can't detect the forms, it won't be able to fill in.
