### ISSUE TITLE
Feature Request: deactivate keyboard shortcut quick switch when specific app window is in focus. 

### ISSUE THREAD

**Issue by eegil** [quanglam2807/webcatalog#1615]
I love the feature of quickly switching to the web app window via keyboard shortcuts, however, this interacts with other apps. 
It would be lovely to have the option the add an option to ignore the shortcut when a specific app window is active. For example when VS Code window is in focus, then the shortcut should inactivate and reactivate immediately when VS Code is out of focus.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
