### ISSUE TITLE
bug: Show Navigation bar/Sidebar shortcuts don't work on Polish keyboard

### ISSUE THREAD

**Issue by maxoku** [quanglam2807/webcatalog#1616]
# Bug Report
**Specifications:**
- WebCatalog Version: v40.3.0 (x64)
- Neutron Version: 21.12.0
- OS (macOS, Windows, Linux): Windows 8.1

**Description:**

Keyboard shortcuts for showing/hiding Navigation bar/Sidebar don't work if a Polish keyboard is set. Keys Ctrl+Alt are used for national letters, so it seems this combination of buttons is blocked by that.

**Steps to Reproduce:**

1. Switch to Polish keyboard
2. Press Alt+Ctrl+N or Alt+Ctrl+S.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
