### ISSUE TITLE
bug: Apps switch to secondary graphic card

### ISSUE THREAD

**Issue by maxoku** [quanglam2807/webcatalog#1617]
# Bug Report
**Specifications:**
- WebCatalog Version: v40.3.0 (x64)
- Neutron Version: 21.12.0
- OS (macOS, Windows, Linux): Windows 8.1

**Description:**

Apps can switch to my secondary graphic card (NVIDIA) on my laptop while working and stay that way till I close them. They start normally with the primary (integrated) graphic card (Intel) and setting it to always start with it doesn't change anything. Diode on my laptop change color from blue to orange and tray icon shows that an app is using it, but without specifying which one in this case. It goes back to normal when I close the app.

Disabling hardware acceleration makes it start that way, so maybe for some reason it disables itself while working?
When switched to secondary graphic card it might use more CPU than usual. I saw that also on browsers that for some reason more CPU is used when working on it.

I would like it to not switch to the secondary graphic card or if it has to do that, it would switch back to primary one. It's frustrating that the diode is changing and I have to reset the app to fix that.

It happens randomly, so there are no steps to reproduce.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
