### ISSUE TITLE
Support for latest Node LTS ?

### ISSUE THREAD

**Issue by vesper8** [quanglam2807/webcatalog#1618]
Latest LTS Version is 16.13.2

Yet I get this error when trying to run `yarn`: `error WebCatalog@40.3.0: The engine "node" is incompatible with this module. Expected version ">=14.0.0 <15.0.0". Got "16.13.2"`

Any chance you will update it to use the latest LTS?

Thanks!

**Comment by quanglam2807** [comment]
You can just remove the engine requirement from `package.json`. The app should run with Node 16. We'll try to migrate officially to 16 in the future
