### ISSUE TITLE
Forgets the window's size and position when pinned to the tray

### ISSUE THREAD

**Issue by maxoku** [quanglam2807/webcatalog#1626]
The size and position of the window when pinned to the tray is being forget upon the restart. It sometimes remember after one restart but usually it forgets and starts from the top left corner of the screen with default size. It would be nice if it would remember the size and position always till the option to pin window to system tray is turned off.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
