### ISSUE TITLE
bug: Google Meet video filters aren't available

### ISSUE THREAD

**Issue by palradu** [quanglam2807/webcatalog#1628]
Hello,

When using Google Meet, if I try to apply a video filter, it shows an error that I am not using a browser that can use video filters. Is there any way to add this capability, so that we can use this feature of Google Meet? It's really important when working from home.
![image](https://user-images.githubusercontent.com/9775016/152376284-a30f28d0-18fe-4be8-bf7f-cf43ac9a576b.png)

**Comment by palradu** [comment]
It seems that it was a user agent issue. Visual filters work only with the Chrome user agent, so after changing this in the app, it works. Maybe it would be a good idea to force the Meet app to always use Chrome user agents, if possible, of course.

**Comment by quanglam2807** [comment]
I'm sorry but the user-agent change is intentional to keep Google Meet functioning properly and in the moment, it's not possible to use video filters with WebCatalog + Google Meet.
