### ISSUE TITLE
hi！ How do I use it?

### ISSUE THREAD

**Issue by Johnhacker** [quanglam2807/webcatalog#3]

**Comment by quanglam2807** [comment]
Hi, so just choose an app you like, download the installer and follow the instruction on the website. :dancer:

**Comment by Johnhacker** [comment]
e，my mean is ，how can I use it  on my server，I want to build a site like webcatalog.xyz

**Comment by quanglam2807** [comment]
The project is still in beta so I haven't provided a clear document yet but basically, after you fork the project, setup Travis, SourceForge, Algolia, Surge and then update the variables in `travis.yml` and you're good to go! You can also contact me via email quang.lam2807@gmail.com or Skype quanglam2807
