### ISSUE TITLE
Request for new app: Roam Research

### ISSUE THREAD

**Issue by beorn** [quanglam2807/webcatalog#384]
https://roamresearch.com/#/app

a very cool online outliner+wiki system

**Comment by quanglam2807** [comment]
![Artboard](https://user-images.githubusercontent.com/1548835/69018111-5bd69c80-0970-11ea-8f5a-a0d661496f4c.png)

Would that icon work? I cannot find a better one :(

**Comment by beorn** [comment]
Yes,  that’s the best they have :-/
