### ISSUE TITLE
app: read.amazon.com

### ISSUE THREAD

**Issue by beorn** [quanglam2807/webcatalog#407]
# App Submission

- **Name:** Amazon Kindle CloudReader
- **URL:** read.amazon.com
- **Category:**

- **Icon:**

**Comment by quanglam2807** [comment]
![ios-icon (1)](https://user-images.githubusercontent.com/1548835/69498939-0b50c900-0eb3-11ea-93d3-cc6bf514d1ef.png)
This is the best I could find for the icon :(
