### ISSUE TITLE
app: Yandex Music

### ISSUE THREAD

**Issue by Wesley444** [quanglam2807/webcatalog#546]
# App Submission

- **Name:** Yandex Music
- **URL:**https://music.yandex.ru/home
- **Category:**Social Networking 

- **Icon:**
![Yandex music Icon](https://user-images.githubusercontent.com/61077862/74584433-00519480-4fdb-11ea-8416-8796ce910011.png)

**Comment by Wesley444** [comment]
Please guys, add this one! Much better and cheaper than Apple music.

Thank you!

**Comment by quanglam2807** [comment]
@Wesley444 Thanks for the submission! Have you tried to see if works with WebCatalog? I'm just afraid it might have DRM protection

**Comment by Wesley444** [comment]
Yes, I tried to build it on Electron. But then click login button it an open page in a browser. So can't log in to an account. I think they don't have DRM. It is a subscription service.

**Comment by quanglam2807** [comment]
Thank you! That’s a bug. Can you send me the link that was open in browser? Yandex Music is not available in the US so I can’t test it myself

**Comment by Wesley444** [comment]
Here it is:
https://clck.yandex.ru/redir/dtype=stred/pid=616/cid=123/pageID=95003951115817993439840580354080715/experiment=on/*https://passport.yandex.ru/auth?origin=music_button-header&retpath=https%3A%2F%2Fmusic.yandex.ru%2Fsettings%3Freqid%3D95003951115817993439840580354080715%26from-passport

**Comment by Wesley444** [comment]
The link above is after then click on Log in button in app

Here is the link of their website: https://music.yandex.ru/home

**Comment by quanglam2807** [comment]
Thank you for information! The bug fix will be available in the next update. I'll also add the app to the catalog soon.

**Comment by Wesley444** [comment]
Hooray!!!

Thanks! Much appreciate it!
